server:
  port: 10080
spring:
  application:
    name: cloud-platform-report
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  config:
    import:
      - "nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}"
#      - "nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}"
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER  # 切换为Ant路径匹配器，兼容Springfox
  maxinhai:
    enable: true
    name: 666先生的救赎